BalancedDatasets-COCO:
  class: 79
  performance_file: coco_mAP.yaml
  settings: !!python/tuple
  - - threshold_0.5/no_gender/
  - - threshold_0.5/ratio-1/
    - threshold_0.5/ratio-2/
    - threshold_0.5/ratio-3/
    - threshold_0.5/adv-conv4/
    - threshold_0.5/adv-conv5/
BalancedDatasets-imSitu:
  class: 211
  performance_file: imSitu_mAP.yaml
  settings: !!python/tuple
  - - no_gender/
  - - ratio-1/
    - ratio-2/
    - ratio-3/
    - adv-conv4/
    - adv-conv5/
EffStrategies:
  class: 10
  performance_file: cifar-10s.yaml
  settings: !!python/tuple
  - - baseline/
  - - sampling/
    - uniconf-adv/
    - gradproj-adv/
    - domain-discriminative/Sum-of-prob-no-prior-shift/
    - domain-discriminative/Max-of-prob-prior-shift/
    - domain-discriminative/Sum-of-prob-prior-shift/
    - domain-discriminative/rba/
    - domain-independent/Conditional/
    - domain-independent/Sum/
FairALM-CelebA:
  class: 2
  performance_file: celeba_alm_acc.yaml
  settings: !!python/tuple
  - - no-constraints/
  - - l2-penalty/
    - fair-alm/
NIFR:
  class: 2
  performance_file: celeba_nifr_acc.yaml
  settings: !!python/tuple
  - - baseline/
  - - inn/
